"""initial schema

Revision ID: 5a708c4135d2
Revises: 
Create Date: 2026-04-21 17:22:47.112887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a708c4135d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('primary_muscles', sa.JSON(), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=False),
    sa.Column('movement_pattern', sa.String(length=64), nullable=False),
    sa.Column('equipment_tags', sa.JSON(), nullable=False),
    sa.Column('environment_tags', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('impact_level', sa.String(length=32), nullable=False),
    sa.Column('contraindication_tags', sa.JSON(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_id', name='uq_exercises_source_record')
    )
    op.create_index(op.f('ix_exercises_difficulty'), 'exercises', ['difficulty'], unique=False)
    op.create_index(op.f('ix_exercises_impact_level'), 'exercises', ['impact_level'], unique=False)
    op.create_index(op.f('ix_exercises_movement_pattern'), 'exercises', ['movement_pattern'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_index(op.f('ix_exercises_owner_user_id'), 'exercises', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_exercises_source_name'), 'exercises', ['source_name'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Enum('MUSCLE_GAIN', 'STRENGTH', 'GENERAL_FITNESS', name='goal', native_enum=False), nullable=False),
    sa.Column('split', sa.Enum('FULL_BODY', 'UPPER_LOWER', 'PUSH_PULL_LEGS', name='plansplit', native_enum=False), nullable=False),
    sa.Column('training_days_per_week', sa.Integer(), nullable=False),
    sa.Column('environment', sa.Enum('HOME', 'GYM', name='environment', native_enum=False), nullable=False),
    sa.Column('generation_mode', sa.String(length=64), nullable=False),
    sa.Column('request_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_revision_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_user_id'), 'training_plans', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('training_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='traininglevel', native_enum=False), nullable=True),
    sa.Column('preferred_environment', sa.Enum('HOME', 'GYM', name='environment', native_enum=False), nullable=True),
    sa.Column('primary_goal', sa.Enum('MUSCLE_GAIN', 'STRENGTH', 'GENERAL_FITNESS', name='goal', native_enum=False), nullable=True),
    sa.Column('training_days_per_week', sa.Integer(), nullable=True),
    sa.Column('available_equipment', sa.JSON(), nullable=False),
    sa.Column('discomfort_tags', sa.JSON(), nullable=False),
    sa.Column('blocked_exercise_ids', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=120), nullable=False),
    sa.Column('focus_summary', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'day_index', name='uq_plan_day_index')
    )
    op.create_index(op.f('ix_workout_sessions_plan_id'), 'workout_sessions', ['plan_id'], unique=False)
    op.create_table('workout_session_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('slot_type', sa.String(length=64), nullable=False),
    sa.Column('selection_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.String(length=32), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_session_exercises_exercise_id'), 'workout_session_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_session_exercises_session_id'), 'workout_session_exercises', ['session_id'], unique=False)
    op.create_table('adjustment_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_exercise_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('DISLIKE', 'PAIN_OR_DISCOMFORT', 'EQUIPMENT_UNAVAILABLE', 'TOO_DIFFICULT', 'ENVIRONMENT_MISMATCH', 'WANTS_VARIETY', name='adjustmentreason', native_enum=False), nullable=False),
    sa.Column('detail_note', sa.Text(), nullable=False),
    sa.Column('override_environment', sa.Enum('HOME', 'GYM', name='environment', native_enum=False), nullable=True),
    sa.Column('temporary_unavailable_equipment', sa.JSON(), nullable=False),
    sa.Column('temporary_discomfort_tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['workout_session_exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjustment_requests_plan_id'), 'adjustment_requests', ['plan_id'], unique=False)
    op.create_index(op.f('ix_adjustment_requests_session_exercise_id'), 'adjustment_requests', ['session_exercise_id'], unique=False)
    op.create_index(op.f('ix_adjustment_requests_session_id'), 'adjustment_requests', ['session_id'], unique=False)
    op.create_table('workout_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('exercise_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('slot_type_snapshot', sa.String(length=64), nullable=False),
    sa.Column('movement_pattern_snapshot', sa.String(length=64), nullable=False),
    sa.Column('planned_sets', sa.Integer(), nullable=False),
    sa.Column('planned_reps', sa.String(length=32), nullable=False),
    sa.Column('planned_rest_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_sets', sa.Integer(), nullable=False),
    sa.Column('completed_reps_total', sa.Integer(), nullable=False),
    sa.Column('completion_status', sa.Enum('COMPLETED', 'PARTIAL', 'SKIPPED', name='workoutcompletionstatus', native_enum=False), nullable=False),
    sa.Column('effort_rating', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('performed_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['workout_session_exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_exercise_id', name='uq_workout_log_session_exercise')
    )
    op.create_index(op.f('ix_workout_logs_completion_status'), 'workout_logs', ['completion_status'], unique=False)
    op.create_index(op.f('ix_workout_logs_exercise_id'), 'workout_logs', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_logs_performed_on'), 'workout_logs', ['performed_on'], unique=False)
    op.create_index(op.f('ix_workout_logs_plan_id'), 'workout_logs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_workout_logs_session_exercise_id'), 'workout_logs', ['session_exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_logs_session_id'), 'workout_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_workout_logs_user_id'), 'workout_logs', ['user_id'], unique=False)
    op.create_table('plan_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_request_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('old_exercise_id', sa.Integer(), nullable=False),
    sa.Column('new_exercise_id', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('before_snapshot', sa.JSON(), nullable=False),
    sa.Column('after_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['adjustment_request_id'], ['adjustment_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['old_exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adjustment_request_id'),
    sa.UniqueConstraint('plan_id', 'revision_number', name='uq_plan_revision_number')
    )
    op.create_index(op.f('ix_plan_revisions_plan_id'), 'plan_revisions', ['plan_id'], unique=False)
    op.create_table('plan_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('explanation_scope', sa.Enum('PLAN', 'REVISION', name='explanationscope', native_enum=False), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['plan_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_explanations_explanation_scope'), 'plan_explanations', ['explanation_scope'], unique=False)
    op.create_index(op.f('ix_plan_explanations_plan_id'), 'plan_explanations', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_explanations_revision_id'), 'plan_explanations', ['revision_id'], unique=False)
    op.create_index(op.f('ix_plan_explanations_user_id'), 'plan_explanations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_explanations_user_id'), table_name='plan_explanations')
    op.drop_index(op.f('ix_plan_explanations_revision_id'), table_name='plan_explanations')
    op.drop_index(op.f('ix_plan_explanations_plan_id'), table_name='plan_explanations')
    op.drop_index(op.f('ix_plan_explanations_explanation_scope'), table_name='plan_explanations')
    op.drop_table('plan_explanations')
    op.drop_index(op.f('ix_plan_revisions_plan_id'), table_name='plan_revisions')
    op.drop_table('plan_revisions')
    op.drop_index(op.f('ix_workout_logs_user_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_session_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_session_exercise_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_plan_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_performed_on'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_exercise_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_completion_status'), table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_index(op.f('ix_adjustment_requests_session_id'), table_name='adjustment_requests')
    op.drop_index(op.f('ix_adjustment_requests_session_exercise_id'), table_name='adjustment_requests')
    op.drop_index(op.f('ix_adjustment_requests_plan_id'), table_name='adjustment_requests')
    op.drop_table('adjustment_requests')
    op.drop_index(op.f('ix_workout_session_exercises_session_id'), table_name='workout_session_exercises')
    op.drop_index(op.f('ix_workout_session_exercises_exercise_id'), table_name='workout_session_exercises')
    op.drop_table('workout_session_exercises')
    op.drop_index(op.f('ix_workout_sessions_plan_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_training_plans_user_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_exercises_source_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_owner_user_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_movement_pattern'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_impact_level'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_difficulty'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
